export enum TipoNotificacion {
  NOTIFCACION_ATRASOS = 100,
  NOTIFICACION_FALTAS = 101,
  NOTIFICACION_SALIDAS_ANTICIPADAS = 102,
  COMUNICADOS = 6,

  // PERMISOS
  CREAR_PERMISO = 1,
  EDITAR_PERMISO = 2,
  ELIMINAR_PERMISO = 3,
  PREAUTORIZAR_PERMISO = 4,
  AUTORIZAR_PERMISO = 5,
  RECHAZAR_PERMISO = 7,
  LEGALIZAR_PERMISO = 8,

  // VACACIONES
  CREAR_VACACION = 9,
  EDITAR_VACACION = 10,
  ELIMINAR_VACACION = 11,
  PREAUTORIZAR_VACACION = 12,
  AUTORIZAR_VACACION = 13,
  RECHAZAR_VACACION = 14,
}